
name: nexos-frontend
services:
  nexos-frontend:
    container_name: nexos-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
