services:
  payments-webapi:
    image: ${DOCKER_REGISTRY-}payments-webapi
    container_name: payments-webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      postgres-payments:
        condition: service_healthy
    ports:
      - 5000:8080
  postgres-payments:
    image: postgres:17
    container_name: postgres-payments
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
