services:
  payments-webapi:
    image: ${DOCKER_REGISTRY-}payments-webapi
    container_name: payments-webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      payments-postgres:
        condition: service_healthy
    ports:
      - 5000:8080
  payments-postgres:
    image: postgres:17
    container_name: payments-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
